services:
  sodev:
    container_name: pg_sodev
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=sodev
  devcache:
    container_name: dcache
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./cache/dcache:/data

  sotest:
    container_name: pg_sotest
    image: postgres:latest
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=sotest

  testcache:
    container_name: tcache
    image: redis:latest
    ports:
      - 6479:6379
    volumes:
      - ./cache/tcache:/data
